from typing import Callable,Optional,Dict
import tkinter as tk
from tkinter import ttk
import tkinter.font as tkfont
from tkinter import simpledialog
from tkinter import messagebox

# helper class to manage universal Dialog Windows	
class ModalDialog(simpledialog.Dialog):
    def __init__(self, parent, title, resultFun:Optional[Callable[[bool],bool]]=None, oneOkButton=False, buttonOkCancelActions:Optional[Dict[str,Callable]]=None):
        """Constructor for ModalDialog creation.

        Args:
            parent (tk.Frame): the parent frame to which the dialog is connected
            title (str): window title
            resultFun (bool, optional): End of modal dialog window result handler function. Defaults to None. 
                If given, the result function have to return one of the values:
                    - True if the dialog should be destroyed
                    - False if not
        """
        self._result=False
        self._resultFun=resultFun
        self._oneOkButton=oneOkButton
        self.buttonOkCancelActions=buttonOkCancelActions
        super().__init__(parent, title)
    
    def getResult(self): 
        """Returns the result of the dialog.

        Returns:
            bool: result of the dialog
        """
        return self._result
    
    def getResult(self):
        return self._result
    
    def setResult(self, value):
        self._result = value

    def onOK(self,event):
        """End of the dialog window by pushing the OK button - event handler.

        Args:
            event (tk.Event): automatically generated by the tk library event
        """
        self._result=True
        if self._resultFun!=None:
            self._proceedExit=self._resultFun(self._result)
        if type(self._proceedExit) != bool or self._proceedExit:
            self.destroy()
    
    def onCancel(self,event): 
        """End of the dialog window by pushing the cancel button - event handler.

        Args:
            event (tk.Event): automatically generated by the tk library event
        """
        self._result=False
        if self._resultFun!=None:
            self._resultFun(self._result)
        self.destroy()

    def buttonbox(self):
        """Dialog windows footer standard cancel/ok or just ok buttons to finalise the dialog.
        (this methid could be overwritten in inheritance code if needed)
        """
        self.__onOKButton = tk.Button(self, text='OK', width=5)
        self.__onOKButton.pack(side="left",padx=5,pady=5)
        self.__onOKButton.bind("<Button-1>", lambda event: self.onOK(event))
        if not self._oneOkButton:
            self.__onCancelButton = tk.Button(self, text='Cancel', width=5)
            self.__onCancelButton.pack(side="right",padx=5,pady=5)
            self.__onCancelButton.bind("<Button-1>", lambda event: self.onCancel(event))

if __name__ == "__main__":

    # dialog window class to manage offer checking feature
    class SampleSimpleModalDialog(ModalDialog):
        # constructor
        #	selectedVehiclesList - the list of vehicles to do offer checking
        #	businessLoginObj=None - reference to class providing methods to handle of vehicles
        def __init__(self,parent):
            self.foo='aaa'
            self.bar='bbb'
            super().__init__(parent,"Login to app",self.showResults)
        
        def showResults(self,result): # shows the results for every vehicle price offer
            if result==True:
                self.foo=self._foo_ref.get()
                self.bar=self._bar_ref.get()
            print(f"FROM INSIDE OF CHECKOFFERDIALOG, data {'confirmed: '+self.foo+', '+self.bar if result else 'unconfirmed'}")
            return result # False means, dialog can never be closed by clicking OK button, user have to choose Cancel to close the windows
        
        def body(self, frame): # designs the window widgets
            self.__frame=frame

            # foo label
            _label1=tk.Label(frame,text='Login:')
            _label1.grid(row=0,column=0,columnspan=2,ipady=10,sticky='w')

            self._foo_ref=tk.StringVar(frame,"")
            self._foo_ref.set(self.foo)
            _foo_entry=tk.Entry(frame,textvariable=self._foo_ref)
            _foo_entry.grid(row=1,column=0,columnspan=2,ipady=10,sticky='ew')

            _label2=tk.Label(frame,text='Password:')
            _label2.grid(row=2,column=0,columnspan=2,ipady=10,sticky='w')

            self._bar_ref=tk.StringVar(frame,"")
            self._bar_ref.set(self.bar)
            _bar_entry=tk.Entry(frame,textvariable=self._bar_ref)
            _bar_entry.grid(row=3,column=0,columnspan=2,ipady=10,sticky='ew')

            return frame

    def manageSampleSimpleModalDialog(event):
        print("call the CheckOfferDialog")
        result=SampleSimpleModalDialog(root)
        print("FROM MAIN PROCESS, result:",result)

    root=tk.Tk() # initialisation of the Tk library
    sampleButton=tk.Button(root,text='Simple Modal Dialog')
    sampleButton.pack(padx=35,pady=35)
    sampleButton.bind("<Button-1>",lambda event: manageSampleSimpleModalDialog(event))

    tk.mainloop()
